var averageBN = 48273,
    averageOPP = 79921,
    averageNat = 61103,
    colorBN = "#304FFE",
    colorOPP = "#ff1744",
    colorUser = "#FFEA00",
    colorOpponent = "#1DE9B6";

var dataAll = [
    {kod:"P125", seat:"Putrajaya", name:"Tengku Adnan Tengku Mansor", party:"BN-UMNO", y:17925, color:colorBN, level:100, state:"Putrajaya", kelas:"Urban"},
    {kod:"P207", seat:"Igan", name:"Wahab Dolah", party:"BN-PBB", y:18334, color:colorBN, level:100, state:"Sarawak", kelas:"Rural"},
    {kod:"P222", seat:"Lawas", name:"Henry Sum Agong", party:"BN-PBB", y:19896, color:colorBN, level:99, state:"Sarawak", kelas:"Rural"},
    {kod:"P210", seat:"Kanowit", name:"Aaron Ago Dagang", party:"BN-PRS", y:20052, color:colorBN, level:98, state:"Sarawak", kelas:"Rural"},
    {kod:"P206", seat:"Tanjong Manis", name:"Norah Abd. Rahman", party:"BN-PBB", y:20190, color:colorBN, level:98, state:"Sarawak", kelas:"Rural"},
    {kod:"P203", seat:"Lubok Antu", name:"William Nyallau Badak ", party:"BN-PRS", y:20362, color:colorBN, level:98, state:"Sarawak", kelas:"Rural"},
    {kod:"P200", seat:"Batang Sadong", name:"Nancy Shukri", party:"BN-PBB", y:21693, color:colorBN, level:97, state:"Sarawak", kelas:"Rural"},
    {kod:"P209", seat:"Julau", name:"Joseph Salang Gandum", party:"BN-PRS", y:23577, color:colorBN, level:96, state:"Sarawak", kelas:"Rural"},
    {kod:"P183", seat:"Beluran", name:"Ronald Kiandee", party:"BN-UMNO", y:24938, color:colorBN, level:95, state:"Sabah", kelas:"Rural"},
    {kod:"P166", seat:"Labuan", name:"Rozman Isli", party:"BN-UMNO", y:25087, color:colorBN, level:95, state:"Labuan", kelas:"Semi-urban"},
    {kod:"P221", seat:"Limbang", name:"Hasbi Habibollah", party:"BN-PBB", y:25199, color:colorBN, level:95, state:"Sarawak", kelas:"Rural"},
    {kod:"P187", seat:"Kinabatangan", name:"Bung Moktar Radin", party:"BN-UMNO", y:25315, color:colorBN, level:94, state:"Sabah", kelas:"Rural"},
    {kod:"P216", seat:"Hulu Rajang", name:"Wilson Ugak Kumbong", party:"BN-PRS", y:25316, color:colorBN, level:94, state:"Sarawak", kelas:"Rural"},
    {kod:"P181", seat:"Tenom", name:"Raime Unggi", party:"BN-UMNO", y:25340, color:colorBN, level:94, state:"Sabah", kelas:"Rural"},
    {kod:"P192", seat:"Mas Gading", name:"Nogeh Gumbek", party:"BN-SPDP", y:26926, color:colorBN, level:93, state:"Sarawak", kelas:"Rural"},
    {kod:"P176", seat:"Kimanis", name:"Anifah Aman", party:"BN-UMNO", y:26958, color:colorBN, level:93, state:"Sabah", kelas:"Rural"},
    {kod:"P182", seat:"Pensiangan", name:"Joseph Kurup", party:"BN-PBRS", y:27058, color:colorBN, level:93, state:"Sabah", kelas:"Rural"},
    {kod:"P078", seat:"Cameron Highlands", name:"G. Palanivel", party:"BN-MIC", y:27941, color:colorBN, level:92, state:"Pahang", kelas:"Rural"},
    {kod:"P204", seat:"Betong", name:"Douglas Uggah Embas", party:"BN-PBB", y:28072, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P055", seat:"Lenggong", name:"Shamsul Anuar Nasarah", party:"BN-UMNO", y:28148, color:colorBN, level:92, state:"Perak", kelas:"Rural"},
    {kod:"P214", seat:"Selangau", name:"Joseph Entulu Belaun", party:"BN-PRS", y:28271, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P201", seat:"Batang Lupar", name:"Rohani Abdul Karim", party:"BN-PBB", y:28642, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P213", seat:"Mukah", name:"Muhammad Leo Michael Toyad Abdullah", party:"BN-PBB", y:28714, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P215", seat:"Kapit", name:"Alexander Nanta Linggi", party:"BN-PBB", y:28719, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P061", seat:"Padang Rengas", name:"Mohamed Nazri Abdul Aziz", party:"BN-UMNO", y:28830, color:colorBN, level:92, state:"Perak", kelas:"Rural"},
    {kod:"P205", seat:"Saratok", name:"William Mawan Ikom", party:"BN", y:28843, color:colorBN, level:92, state:"Sarawak", kelas:"Rural"},
    {kod:"P178", seat:"Sipitang", name:"Sapawi Ahmad Wasali", party:"BN-UMNO", y:29470, color:colorBN, level:91, state:"Sabah", kelas:"Rural"},
    {kod:"P218", seat:"Sibuti", name:"Ahmad Lai Bujang", party:"BN-PBB", y:29974, color:colorBN, level:91, state:"Sarawak", kelas:"Rural"},
    {kod:"P177", seat:"Beaufort", name:"Azizah Mohd. Dun", party:"BN-UMNO", y:30218, color:colorBN, level:91, state:"Sabah", kelas:"Rural"},
    {kod:"P185", seat:"Batu Sapi", name:"Linda Tsen Thau Lin", party:"BN-PBS", y:30389, color:colorBN, level:91, state:"Sabah", kelas:"Rural"},
    {kod:"P202", seat:"Sri Aman", name:"Masir Kujat", party:"BN-PRS", y:31147, color:colorBN, level:90, state:"Sarawak", kelas:"Rural"},
    {kod:"P079", seat:"Lipis", name:"Abdul Rahman Mohamad", party:"BN-UMNO", y:32222, color:colorBN, level:89, state:"Pahang", kelas:"Rural"},
    {kod:"P067", seat:"Kuala Kangsar", name:"Mastura Mohd Yazid", party:"BN-UMNO", y:33066, color:colorBN, level:89, state:"Perak", kelas:"Semi-urban"},
    {kod:"P069", seat:"Parit", name:"Mohd Zaim Abu Hasan", party:"BN-UMNO", y:33485, color:colorBN, level:88, state:"Perak", kelas:"Rural"},
    {kod:"P054", seat:"Gerik", name:"Hasbullah Osman", party:"BN-UMNO", y:33982, color:colorBN, level:88, state:"Perak", kelas:"Rural"},
    {kod:"P220", seat:"Baram", name:"Anyi Ngau", party:"BN-SPDP", y:34096, color:colorBN, level:88, state:"Sarawak", kelas:"Rural"},
    {kod:"P199", seat:"Serian", name:"Richard Riot Jaem", party:"BN-SUPP", y:35422, color:colorBN, level:87, state:"Sarawak", kelas:"Rural"},
    {kod:"P092", seat:"Sabak Bernam", name:"Mohd Fasiah Mohd Fakeh", party:"BN-UMNO", y:37293, color:colorBN, level:85, state:"Selangor", kelas:"Rural"},
    {kod:"P142", seat:"Labis", name:"Chua Tee Yong", party:"BN-MCA", y:37448, color:colorBN, level:85, state:"Johor", kelas:"Rural"},
    {kod:"P208", seat:"Sarikei", name:"Wong Ling Biu", party:"DAP", y:37454, color:colorOPP, level:85, state:"Sarawak", kelas:"Semi-urban"},
    {kod:"P004", seat:"Langkawi", name:"Nawawi Ahmad", party:"BN-UMNO", y:37632, color:colorBN, level:85, state:"Kedah", kelas:"Rural"},
    {kod:"P186", seat:"Sandakan", name:"Stephen Wong Tien Fatt", party:"DAP", y:37778, color:colorOPP, level:85, state:"Sabah", kelas:"Semi-urban"},
    {kod:"P086", seat:"Maran", name:"Ismail Abd. Muttalib", party:"BN-UMNO", y:37931, color:colorBN, level:85, state:"Pahang", kelas:"Rural"},
    {kod:"P157", seat:"Pengerang", name:"Azalina Othman Said", party:"BN-UMNO", y:38281, color:colorBN, level:85, state:"Johor", kelas:"Rural"},
    {kod:"P173", seat:"Putatan", name:"Marcus Makin Mojigoh", party:"BN-UPKO", y:38284, color:colorBN, level:85, state:"Sabah", kelas:"Semi-urban"},
    {kod:"P175", seat:"Papar", name:"Rosnah Abdul Rashid Shirlin", party:"BN-UMNO", y:39199, color:colorBN, level:84, state:"Sabah", kelas:"Rural"},
    {kod:"P075", seat:"Bagan Datok", name:"Ahmad Zahid Hamidi", party:"BN-UMNO", y:39426, color:colorBN, level:84, state:"Perak", kelas:"Rural"},
    {kod:"P179", seat:"Ranau", name:"Ewon Ebin", party:"BN-UPKO", y:39485, color:colorBN, level:84, state:"Sabah", kelas:"Rural"},
    {kod:"P151", seat:"Simpang Renggam", name:"Liang Teck Meng", party:"BN-GERAKAN", y:40588, color:colorBN, level:83, state:"Johor", kelas:"Rural"},
    {kod:"P155", seat:"Tenggara", name:"Halimah Mohd Sadique", party:"BN-UMNO", y:40849, color:colorBN, level:83, state:"Johor", kelas:"Rural"},
    {kod:"P153", seat:"Sembrong", name:"Hishammuddin Hussein", party:"BN-UMNO", y:41677, color:colorBN, level:82, state:"Johor", kelas:"Rural"},
    {kod:"P141", seat:"Sekijang", name:"Anuar Abd. Manap", party:"BN-UMNO", y:41938, color:colorBN, level:82, state:"Johor", kelas:"Rural"},
    {kod:"P184", seat:"Libaran", name:"Juslie Ajirol", party:"BN-UMNO", y:41963, color:colorBN, level:82, state:"Sabah", kelas:"Rural"},
    {kod:"P032", seat:"Gua Musang", name:"Tengku Razaleigh Hamzah", party:"BN-UMNO", y:42323, color:colorBN, level:82, state:"Kelantan", kelas:"Rural"},
    {kod:"P001", seat:"Padang Besar", name:"Zahidi Zainul Abidin", party:"BN-UMNO", y:42338, color:colorBN, level:82, state:"Perlis", kelas:"Rural"},
    {kod:"P193", seat:"Santubong", name:"Wan Junaidi Tuanku Jaafar", party:"BN-PBB", y:42342, color:colorBN, level:82, state:"Sarawak", kelas:"Rural"},
    {kod:"P197", seat:"Kota Samarahan", name:"Rubiah Wang", party:"BN-PBB", y:42357, color:colorBN, level:82, state:"Sarawak", kelas:"Rural"},
    {kod:"P168", seat:"Kota Marudu", name:"Maximus Johnity Ongkili", party:"BN-PBS", y:42553, color:colorBN, level:81, state:"Sabah", kelas:"Rural"},
    {kod:"P189", seat:"Semporna", name:"Mohd. Shafie Apdal", party:"WARISAN", y:42570, color:colorOPP, level:81, state:"Sabah", kelas:"Rural"},
    {kod:"P095", seat:"Tanjong Karang", name:"Noh Omar", party:"BN-UMNO", y:42620, color:colorBN, level:81, state:"Selangor", kelas:"Rural"},
    {kod:"P093", seat:"Sungai Besar", name:"Budiman Mohd Zohdi", party:"BN-UMNO", y:42828, color:colorBN, level:81, state:"Selangor", kelas:"Rural"},
    {kod:"P156", seat:"Kota Tinggi", name:"Noor Ehsanuddin Mohd Harun Narrashid", party:"BN-UMNO", y:42962, color:colorBN, level:81, state:"Johor", kelas:"Rural"},
    {kod:"P007", seat:"Padang Terap", name:"Mahdzir Khalid", party:"BN-UMNO", y:43022, color:colorBN, level:81, state:"Kedah", kelas:"Rural"},
    {kod:"P087", seat:"Kuala Krau", name:"Ismail Mohamed Said", party:"BN-UMNO", y:43026, color:colorBN, level:81, state:"Pahang", kelas:"Rural"},
    {kod:"P198", seat:"Puncak Borneo (previously Mambong)", name:"James Dawos Mamit", party:"BN-PBB", y:43243, color:colorBN, level:81, state:"Sarawak", kelas:"Rural"},
    {kod:"P148", seat:"Ayer Hitam", name:"Wee Ka Siong", party:"BN-MCA", y:43398, color:colorBN, level:81, state:"Johor", kelas:"Rural"},
    {kod:"P003", seat:"Arau", name:"Shahidan Kassim", party:"BN-UMNO", y:44094, color:colorBN, level:80, state:"Perlis", kelas:"Rural"},
    {kod:"P180", seat:"Keningau", name:"Joseph Pairin Kitingan", party:"BN-PBS", y:44284, color:colorBN, level:80, state:"Sabah", kelas:"Rural"},
    {kod:"P030", seat:"Jeli", name:"Mustapa Mohamed", party:"BN-UMNO", y:44564, color:colorBN, level:80, state:"Kelantan", kelas:"Rural"},
    {kod:"P174", seat:"Penampang", name:"Ignatius Dorell Leiking", party:"WARISAN", y:45179, color:colorOPP, level:79, state:"Sabah", kelas:"Rural"},
    {kod:"P154", seat:"Mersing", name:"Abd. Latiff Ahmad", party:"BN-UMNO", y:45411, color:colorBN, level:79, state:"Johor", kelas:"Rural"},
    {kod:"P126", seat:"Jelebu", name:"Zainudin Ismail", party:"BN-UMNO", y:45797, color:colorBN, level:79, state:"Negeri Sembilan", kelas:"Rural"},
    {kod:"P191", seat:"Kalabakan", name:"Abdul Ghapur Salleh", party:"BN-UMNO", y:46195, color:colorBN, level:79, state:"Sabah", kelas:"Rural"},
    {kod:"P072", seat:"Tapah", name:"M. Saravanan", party:"BN-MIC", y:46233, color:colorBN, level:79, state:"Perak", kelas:"Rural"},
    {kod:"P056", seat:"Larut", name:"Hamzah Zainudin", party:"BN-UMNO", y:46242, color:colorBN, level:79, state:"Perak", kelas:"Rural"},
    {kod:"P149", seat:"Sri Gading", name:"Ab. Aziz Kaprawi", party:"BN-UMNO", y:46442, color:colorBN, level:78, state:"Johor", kelas:"Rural"},
    {kod:"P129", seat:"Kuala Pilah", name:"Hasan Malek", party:"BN-UMNO", y:46759, color:colorBN, level:78, state:"Negeri Sembilan", kelas:"Semi-urban"},
    {kod:"P143", seat:"Pagoh", name:"Muhyiddin Mohd. Yassin", party:"PPBM", y:46968, color:colorOPP, level:78, state:"Johor", kelas:"Rural"},
    {kod:"P013", seat:"Sik", name:"Mansor Abdul Rahman", party:"BN-UMNO", y:47047, color:colorBN, level:78, state:"Kedah", kelas:"Rural"},
    {kod:"P167", seat:"Kudat", name:"Abd Rahim Bakri", party:"BN-UMNO", y:47444, color:colorBN, level:78, state:"Sabah", kelas:"Rural"},
    {kod:"P134", seat:"Masjid Tanah", name:"Mas Ermieyati Samsudin", party:"BN-UMNO", y:48124, color:colorBN, level:77, state:"Melaka", kelas:"Rural"},
    {kod:"P068", seat:"Beruas", name:"Ngeh Koo Ham", party:"DAP", y:48435, color:colorOPP, level:77, state:"Perak", kelas:"Rural"},
    {kod:"P146", seat:"Muar", name:"Razali Ibrahim", party:"BN-UMNO", y:48491, color:colorBN, level:77, state:"Johor", kelas:"Rural"},
    {kod:"P140", seat:"Segamat", name:"S. Subramaniam", party:"BN-MIC", y:48718, color:colorBN, level:77, state:"Johor", kelas:"Rural"},
    {kod:"P164", seat:"Pontian", name:"Ahmad Maslan", party:"BN-UMNO", y:48799, color:colorBN, level:77, state:"Johor", kelas:"Rural"},
    {kod:"P170", seat:"Tuaran", name:"Madius Tangau", party:"BN-UPKO", y:49140, color:colorBN, level:76, state:"Sabah", kelas:"Semi-urban"},
    {kod:"P084", seat:"Paya Besar", name:"Abdul Manan Ismail ", party:"BN-UMNO", y:49176, color:colorBN, level:76, state:"Pahang", kelas:"Rural"},
    {kod:"P172", seat:"Kota Kinabalu", name:"Jimmy Wong Sze Phin", party:"DAP", y:49826, color:colorOPP, level:76, state:"Sabah", kelas:"Urban"},
    {kod:"P057", seat:"Parit Buntar", name:"Mujahid Yusof Rawa", party:"AMANAH", y:50020, color:colorOPP, level:76, state:"Perak", kelas:"Rural"},
    {kod:"P049", seat:"Tanjong", name:"Ng Wei Aik", party:"DAP", y:50136, color:colorOPP, level:76, state:"Pulau Pinang", kelas:"Urban"},
    {kod:"P002", seat:"Kangar", name:"Shaharuddin Ismail", party:"BN-UMNO", y:50909, color:colorBN, level:75, state:"Perlis", kelas:"Semi-urban"},
    {kod:"P073", seat:"Pasir Salak", name:"Tajuddin Abdul Rahman", party:"BN-UMNO", y:51243, color:colorBN, level:75, state:"Perak", kelas:"Rural"},
    {kod:"P090", seat:"Bera", name:"Ismail Sabri Yaakob", party:"BN-UMNO", y:51293, color:colorBN, level:75, state:"Pahang", kelas:"Rural"},
    {kod:"P062", seat:"Sungai Siput", name:"Michael Jeyakumar Devaraj", party:"PSM", y:51607, color:colorOPP, level:75, state:"Perak", kelas:"Semi-urban"},
    {kod:"P005", seat:"Jerlun", name:"Othman Aziz", party:"BN-UMNO", y:51681, color:colorBN, level:74, state:"Kedah", kelas:"Rural"},
    {kod:"P169", seat:"Kota Belud", name:"Abdul Rahman Dahlan", party:"BN-UMNO", y:51851, color:colorBN, level:74, state:"Sabah", kelas:"Rural"},
    {kod:"P053", seat:"Balik Pulau", name:"Hilmi Yahaya", party:"BN-UMNO", y:52337, color:colorBN, level:74, state:"Pulau Pinang", kelas:"Rural"},
    {kod:"P188", seat:"Silam", name:"Datu Nasrun Datu Mansur", party:"BN-UMNO", y:52438, color:colorBN, level:74, state:"Sabah", kelas:"Rural"},
    {kod:"P120", seat:"Bukit Bintang", name:"Fong Kui Lun", party:"DAP", y:52753, color:colorOPP, level:74, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P194", seat:"Petra Jaya", name:"Fadillah Yusof", party:"BN-PBB", y:53607, color:colorBN, level:73, state:"Sarawak", kelas:"Rural"},
    {kod:"P041", seat:"Kepala Batas", name:"Reezal Merican Naina Merican", party:"BN-UMNO", y:53723, color:colorBN, level:73, state:"Pulau Pinang", kelas:"Rural"},
    {kod:"P080", seat:"Raub", name:"Mohd Ariff Sabri Abdul Aziz", party:"DAP", y:53748, color:colorOPP, level:73, state:"Pahang", kelas:"Rural"},
    {kod:"P165", seat:"Tanjong Piai", name:"Wee Jeck Seng", party:"BN-MCA", y:53991, color:colorBN, level:73, state:"Johor", kelas:"Rural"},
    {kod:"P023", seat:"Rantau Panjang", name:"Siti Zailah Mohd Yusoff", party:"PAS", y:54262, color:colorOPP, level:73, state:"Kelantan", kelas:"Rural"},
    {kod:"P058", seat:"Bagan Serai", name:"Noor Azmi Ghazali", party:"BN-UMNO", y:54719, color:colorBN, level:72, state:"Perak", kelas:"Rural"},
    {kod:"P091", seat:"Rompin", name:"Hasan Arifin", party:"BN-UMNO", y:54973, color:colorBN, level:72, state:"Pahang", kelas:"Rural"},
    {kod:"P190", seat:"Tawau", name:"Mary Yap Kain Ching", party:"BN-PBS", y:55232, color:colorBN, level:72, state:"Sabah", kelas:"Semi-urban"},
    {kod:"P042", seat:"Tasek Gelugor", name:"Shabudin Yahaya", party:"BN-UMNO", y:55282, color:colorBN, level:72, state:"Pulau Pinang", kelas:"Rural"},
    {kod:"P171", seat:"Sepanggar", name:"Jumat Idris", party:"BN-UMNO", y:55518, color:colorBN, level:72, state:"Sabah", kelas:"Semi-urban"},
    {kod:"P119", seat:"Titiwangsa", name:"Johari Abdul Ghani", party:"BN-UMNO", y:55899, color:colorBN, level:71, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P083", seat:"Kuantan", name:"Fuziah Salleh", party:"PKR", y:56145, color:colorOPP, level:71, state:"Pahang", kelas:"Urban"},
    {kod:"P147", seat:"Parit Sulong", name:"Noraini Ahmad", party:"BN-UMNO", y:56808, color:colorBN, level:71, state:"Johor", kelas:"Rural"},
    {kod:"P133", seat:"Tampin", name:"Shaziman Abu Mansor", party:"BN-UMNO", y:56880, color:colorBN, level:71, state:"Negeri Sembilan", kelas:"Rural"},
    {kod:"P211", seat:"Lanang", name:"Alice Lau Kiong Yieng", party:"DAP", y:57708, color:colorOPP, level:70, state:"Sarawak", kelas:"Rural"},
    {kod:"P081", seat:"Jerantut", name:"Ahmad Nazlan Idris", party:"BN-UMNO", y:57713, color:colorBN, level:70, state:"Pahang", kelas:"Rural"},
    {kod:"P046", seat:"Batu Kawan", name:"Kasthuriraani Patto", party:"DAP", y:59322, color:colorOPP, level:69, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P217", seat:"Bintulu", name:"Tiong King Sing", party:"BN-SPDP", y:60056, color:colorBN, level:68, state:"Sarawak", kelas:"Semi-urban"},
    {kod:"P018", seat:"Kulim-Bandar Baharu", name:"Abd Aziz Sheikh Fadzir", party:"BN-UMNO", y:60481, color:colorBN, level:68, state:"Kedah", kelas:"Semi-urban"},
    {kod:"P196", seat:"Stampin", name:"Julian Tan Kok Ping", party:"DAP", y:60624, color:colorOPP, level:68, state:"Sarawak", kelas:"Urban"},
    {kod:"P027", seat:"Tanah Merah", name:"Ikmal Hisham Abdul Aziz", party:"BN-UMNO", y:61010, color:colorBN, level:67, state:"Kelantan", kelas:"Rural"},
    {kod:"P076", seat:"Telok Intan", name:"Mah Siew Keong", party:"BN-GERAKAN", y:61086, color:colorBN, level:67, state:"Perak", kelas:"Semi-urban"},
    {kod:"P029", seat:"Machang", name:"Ahmad Jazlan Yaakub", party:"BN-UMNO", y:61323, color:colorBN, level:67, state:"Kelantan", kelas:"Rural"},
    {kod:"P047", seat:"Nibong Tebal", name:"Mansor Othman", party:"PKR", y:62162, color:colorOPP, level:67, state:"Pulau Pinang", kelas:"Rural"},
    {kod:"P089", seat:"Bentong", name:"Liow Tiong Lai", party:"BN-MCA", y:62460, color:colorBN, level:66, state:"Pahang", kelas:"Rural"},
    {kod:"P118", seat:"Setiawangsa", name:"Ahmad Fauzi Zahari", party:"BN-UMNO", y:62812, color:colorBN, level:66, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P070", seat:"Kampar", name:"Ko Chung Sen", party:"DAP", y:63419, color:colorOPP, level:66, state:"Perak", kelas:"Semi-urban"},
    {kod:"P096", seat:"Kuala Selangor", name:"Irmohizam Ibrahim", party:"BN-UMNO", y:63920, color:colorBN, level:65, state:"Selangor", kelas:"Rural"},
    {kod:"P077", seat:"Tanjong Malim", name:"Ong Ka Chuan", party:"BN-MCA", y:63990, color:colorBN, level:65, state:"Perak", kelas:"Rural"},
    {kod:"P026", seat:"Ketereh", name:"Annuar Musa", party:"BN-UMNO", y:64426, color:colorBN, level:65, state:"Kelantan", kelas:"Rural"},
    {kod:"P031", seat:"Kuala Krai", name:"Mohd. Hatta Md. Ramli", party:"AMANAH", y:65289, color:colorOPP, level:64, state:"Kelantan", kelas:"Rural"},
    {kod:"P135", seat:"Alor Gajah", name:"Koh Nai Kwong", party:"BN-MCA", y:65956, color:colorBN, level:64, state:"Melaka", kelas:"Rural"},
    {kod:"P006", seat:"Kubang Pasu", name:"Mohd Johari Baharum", party:"BN-UMNO", y:66141, color:colorBN, level:64, state:"Kedah", kelas:"Semi-urban"},
    {kod:"P127", seat:"Jempol", name:"Mohd Isa Abdul Samad", party:"BN-UMNO", y:66386, color:colorBN, level:63, state:"Negeri Sembilan", kelas:"Rural"},
    {kod:"P082", seat:"Indera Mahkota", name:"Fauzi Abdul Rahman", party:"PKR", y:66813, color:colorOPP, level:63, state:"Pahang", kelas:"Semi-urban"},
    {kod:"P020", seat:"Pengkalan Chepa", name:"Izani Husin", party:"PAS", y:66834, color:colorOPP, level:63, state:"Kelantan", kelas:"Semi-urban"},
    {kod:"P088", seat:"Temerloh", name:"Nasrudin Hassan", party:"PAS", y:66986, color:colorOPP, level:63, state:"Pahang", kelas:"Semi-urban"},
    {kod:"P024", seat:"Kubang Kerian", name:"Ahmad Baihaki Atiqullah", party:"PAS", y:66991, color:colorOPP, level:63, state:"Kelantan", kelas:"Rural"},
    {kod:"P116", seat:"Wangsa Maju", name:"Tan Kee Kwong", party:"PKR", y:67188, color:colorOPP, level:63, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P114", seat:"Kepong", name:"Tan Seng Giaw", party:"DAP", y:67956, color:colorOPP, level:62, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P139", seat:"Jasin", name:"Ahmad Hamzah", party:"BN-UMNO", y:68004, color:colorBN, level:62, state:"Melaka", kelas:"Rural"},
    {kod:"P038", seat:"Hulu Terengganu", name:"Jailani Johari", party:"BN-UMNO", y:68650, color:colorBN, level:62, state:"Terengganu", kelas:"Rural"},
    {kod:"P009", seat:"Alor Star", name:"Gooi Hsiao-Leung", party:"PKR", y:68742, color:colorOPP, level:62, state:"Kedah", kelas:"Urban"},
    {kod:"P145", seat:"Bakri", name:"Er Teck Hwa", party:"DAP", y:68838, color:colorOPP, level:61, state:"Johor", kelas:"Semi-urban"},
    {kod:"P132", seat:"Telok Kemang", name:"Kamarul Baharin Abbas", party:"PKR", y:69338, color:colorOPP, level:61, state:"Negeri Sembilan", kelas:"Semi-urban"},
    {kod:"P043", seat:"Bagan", name:"Lim Guan Eng", party:"DAP", y:69371, color:colorOPP, level:61, state:"Pulau Pinang", kelas:"Urban"},
    {kod:"P212", seat:"Sibu", name:"Oscar Ling Chai Yew", party:"DAP", y:69822, color:colorOPP, level:61, state:"Sarawak", kelas:"Semi-urban"},
    {kod:"P144", seat:"Ledang", name:"Hamim Samuri", party:"BN-UMNO", y:70678, color:colorBN, level:60, state:"Johor", kelas:"Rural"},
    {kod:"P011", seat:"Pendang", name:"Othman Abdul", party:"BN-UMNO", y:70820, color:colorBN, level:60, state:"Kedah", kelas:"Rural"},
    {kod:"P123", seat:"Cheras", name:"Tan Kok Wai", party:"DAP", y:71272, color:colorOPP, level:60, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P034", seat:"Setiu", name:"Che Mohamad Zulkifly Jusoh", party:"BN-UMNO", y:71292, color:colorBN, level:60, state:"Terengganu", kelas:"Rural"},
    {kod:"P048", seat:"Bukit Bendera", name:"Zairil Khir Johari", party:"DAP", y:71772, color:colorOPP, level:59, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P059", seat:"Bukit Gantang", name:"Idris Ahmad", party:"PAS", y:72317, color:colorOPP, level:59, state:"Perak", kelas:"Rural"},
    {kod:"P121", seat:"Lembah Pantai", name:"Nurul Izzah Anwar", party:"PKR", y:72675, color:colorOPP, level:59, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P050", seat:"Jelutong", name:"Jeff Ooi Chuan Aun", party:"DAP", y:72837, color:colorOPP, level:58, state:"Pulau Pinang", kelas:"Urban"},
    {kod:"P022", seat:"Pasir Mas", name:"Nik Mohamad Abduh Nik Abdul Aziz", party:"PAS", y:73098, color:colorOPP, level:58, state:"Kelantan", kelas:"Rural"},
    {kod:"P012", seat:"Jerai", name:"Jamil Khir Baharom", party:"BN-UMNO", y:74176, color:colorBN, level:57, state:"Kedah", kelas:"Rural"},
    {kod:"P044", seat:"Permatang Pauh", name:"Wan Azizah Wan Ismail", party:"PKR", y:74545, color:colorOPP, level:57, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P017", seat:"Padang Serai", name:"N. Surendran", party:"PKR", y:74776, color:colorOPP, level:57, state:"Kedah", kelas:"Semi-urban"},
    {kod:"P117", seat:"Segambut", name:"Lim Lip Eng", party:"DAP", y:75440, color:colorOPP, level:56, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P219", seat:"Miri", name:"Michael Teo Yu Keng", party:"PKR", y:75527, color:colorOPP, level:56, state:"Sarawak", kelas:"Semi-urban"},
    {kod:"P033", seat:"Besut", name:"Idris Jusoh", party:"BN-UMNO", y:77266, color:colorBN, level:55, state:"Terengganu", kelas:"Semi-urban"},
    {kod:"P060", seat:"Taiping", name:"Nga Kor Ming", party:"DAP", y:77376, color:colorOPP, level:55, state:"Perak", kelas:"Urban"},
    {kod:"P065", seat:"Ipoh Barat", name:"M. Kulasegaran ", party:"DAP", y:78043, color:colorOPP, level:55, state:"Perak", kelas:"Urban"},
    {kod:"P136", seat:"Tangga Batu", name:"Abu Bakar Mohamad Diah", party:"BN-UMNO", y:78264, color:colorBN, level:54, state:"Melaka", kelas:"Semi-urban"},
    {kod:"P105", seat:"Petaling Jaya Selatan", name:"Hee Loy Sian", party:"PKR", y:78373, color:colorOPP, level:54, state:"Selangor", kelas:"Urban"},
    {kod:"P028", seat:"Pasir Puteh", name:"Nik Mazian Nik Mohamad", party:"PAS", y:78747, color:colorOPP, level:54, state:"Kelantan", kelas:"Rural"},
    {kod:"P131", seat:"Rembau", name:"Khairy Jamaluddin", party:"BN-UMNO", y:79154, color:colorBN, level:54, state:"Negeri Sembilan", kelas:"Semi-urban"},
    {kod:"P064", seat:"Ipoh Timor", name:"Su Keong Siong", party:"DAP", y:80280, color:colorOPP, level:53, state:"Perak", kelas:"Urban"},
    {kod:"P008", seat:"Pokok Sena", name:"Mahfuz Omar", party:"PAS", y:80502, color:colorOPP, level:53, state:"Kedah", kelas:"Rural"},
    {kod:"P195", seat:"Bandar Kuching", name:"Chong Chieng Jen", party:"DAP", y:81037, color:colorOPP, level:52, state:"Sarawak", kelas:"Urban"},
    {kod:"P045", seat:"Bukit Mertajam", name:"Sim Chee Keong", party:"DAP", y:81294, color:colorOPP, level:52, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P085", seat:"Pekan", name:"Mohd. Najib Abdul Razak", party:"BN-UMNO", y:82303, color:colorBN, level:51, state:"Pahang", kelas:"Rural"},
    {kod:"P035", seat:"Kuala Nerus", name:"Mohd Khairuddin Aman Razali", party:"PAS", y:82497, color:colorOPP, level:51, state:"Terengganu", kelas:"Rural"},
    {kod:"P021", seat:"Kota Bharu", name:"Takiyuddin Hassan", party:"PAS", y:82582, color:colorOPP, level:51, state:"Kelantan", kelas:"Urban"},
    {kod:"P099", seat:"Ampang", name:"Zuraida Kamaruddin", party:"PKR", y:83200, color:colorOPP, level:51, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P025", seat:"Bachok", name:"Ahmad Marzuk Shaary", party:"PAS", y:83206, color:colorOPP, level:51, state:"Kelantan", kelas:"Semi-urban"},
    {kod:"P039", seat:"Dungun", name:"Wan Hassan Mohd Ramli", party:"PAS", y:83283, color:colorOPP, level:51, state:"Terengganu", kelas:"Semi-urban"},
    {kod:"P052", seat:"Bayan Baru", name:"Sim Tze Tzin", party:"PKR", y:83594, color:colorOPP, level:50, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P066", seat:"Batu Gajah", name:"V. Sivakumar", party:"DAP", y:83883, color:colorOPP, level:50, state:"Perak", kelas:"Urban"},
    {kod:"P106", seat:"Petaling Jaya Utara", name:"Tony Pua Kiam Wee", party:"DAP", y:84284, color:colorOPP, level:50, state:"Selangor", kelas:"Urban"},
    {kod:"P051", seat:"Bukit Gelugor", name:"Ramkarpal Singh", party:"DAP", y:85053, color:colorOPP, level:49, state:"Pulau Pinang", kelas:"Semi-urban"},
    {kod:"P100", seat:"Pandan", name:"Mohd Rafizi Ramli", party:"PKR", y:85090, color:colorOPP, level:49, state:"Selangor", kelas:"Urban"},
    {kod:"P115", seat:"Batu", name:"Tian Chua", party:"PKR", y:85092, color:colorOPP, level:49, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P122", seat:"Seputeh", name:"Teresa Kok Suh Sim", party:"DAP", y:85172, color:colorOPP, level:49, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P113", seat:"Sepang", name:"Mohamed Hanipa Maidin", party:"AMANAH", y:85853, color:colorOPP, level:49, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P014", seat:"Merbok", name:"Ismail Daut", party:"BN-UMNO", y:86926, color:colorBN, level:48, state:"Kedah", kelas:"Semi-urban"},
    {kod:"P094", seat:"Hulu Selangor", name:"P. Kamalanathan", party:"BN-MIC", y:86966, color:colorBN, level:48, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P163", seat:"Kulai", name:"Teo Nie Ching", party:"DAP", y:87218, color:colorOPP, level:48, state:"Johor", kelas:"Semi-urban"},
    {kod:"P112", seat:"Kuala Langat", name:"Abdullah Sani Abdul Hamid", party:"PKR", y:89077, color:colorOPP, level:46, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P152", seat:"Kluang", name:"Liew Chin Tong", party:"DAP", y:89470, color:colorOPP, level:46, state:"Johor", kelas:"Semi-urban"},
    {kod:"P130", seat:"Rasah", name:"Teo Kok Seong", party:"DAP", y:89496, color:colorOPP, level:46, state:"Negeri Sembilan", kelas:"Urban"},
    {kod:"P074", seat:"Lumut", name:"Mohamad Imran Abdul Hamid", party:"PKR", y:90308, color:colorOPP, level:45, state:"Perak", kelas:"Semi-urban"},
    {kod:"P150", seat:"Batu Pahat", name:"Mohd Idris Jusi", party:"PKR", y:90401, color:colorOPP, level:45, state:"Johor", kelas:"Semi-urban"},
    {kod:"P124", seat:"Bandar Tun Razak", name:"Abd Khalid Ibrahim", party:"BEBAS", y:91379, color:colorOPP, level:44, state:"Kuala Lumpur", kelas:"Urban"},
    {kod:"P063", seat:"Tambun", name:"Ahmad Husni Mohamad Hanadzlah", party:"BN-UMNO", y:92356, color:colorBN, level:44, state:"Perak", kelas:"Semi-urban"},
    {kod:"P015", seat:"Sungai Petani", name:"Johari Abdul", party:"PKR", y:93946, color:colorOPP, level:42, state:"Kedah", kelas:"Semi-urban"},
    {kod:"P138", seat:"Kota Melaka", name:"Sim Tong Him", party:"BEBAS", y:94066, color:colorOPP, level:42, state:"Melaka", kelas:"Urban"},
    {kod:"P010", seat:"Kuala Kedah", name:"Azman Ismail", party:"PKR", y:95137, color:colorOPP, level:42, state:"Kedah", kelas:"Rural"},
    {kod:"P016", seat:"Baling", name:"Abdul Azeez Abdul Rahim", party:"BN-UMNO", y:95349, color:colorBN, level:41, state:"Kedah", kelas:"Rural"},
    {kod:"P037", seat:"Marang", name:"Abdul Hadi Awang", party:"PAS", y:96708, color:colorOPP, level:40, state:"Terengganu", kelas:"Rural"},
    {kod:"P160", seat:"Johor Bahru", name:"Shahrir Abdul Samad", party:"BN-UMNO", y:96923, color:colorBN, level:40, state:"Johor", kelas:"Urban"},
    {kod:"P036", seat:"Kuala Terengganu", name:"Raja Kamarul Bahrin Shah Raja Ahmad", party:"AMANAH", y:96965, color:colorOPP, level:40, state:"Terengganu", kelas:"Urban"},
    {kod:"P110", seat:"Klang", name:"Charles Santiago", party:"DAP", y:98263, color:colorOPP, level:39, state:"Selangor", kelas:"Urban"},
    {kod:"P040", seat:"Kemaman", name:"Ahmad Shabery Cheek", party:"BN-UMNO", y:99432, color:colorBN, level:38, state:"Terengganu", kelas:"Semi-urban"},
    {kod:"P071", seat:"Gopeng", name:"Lee Boon Chye", party:"PKR", y:101225, color:colorOPP, level:37, state:"Perak", kelas:"Semi-urban"},
    {kod:"P104", seat:"Kelana Jaya", name:"Wong Chen", party:"PKR", y:101590, color:colorOPP, level:37, state:"Selangor", kelas:"Urban"},
    {kod:"P158", seat:"Tebrau", name:"Khoo Soo Seang", party:"BN-MCA", y:101916, color:colorBN, level:36, state:"Johor", kelas:"Semi-urban"},
    {kod:"P019", seat:"Tumpat", name:"Kamarudin Jaffar", party:"PKR", y:102372, color:colorOPP, level:36, state:"Kelantan", kelas:"Rural"},
    {kod:"P128", seat:"Seremban", name:"Loke Siew Fook", party:"DAP", y:103795, color:colorOPP, level:35, state:"Negeri Sembilan", kelas:"Urban"},
    {kod:"P108", seat:"Shah Alam", name:"Khalid Abd. Samad ", party:"AMANAH", y:104289, color:colorOPP, level:35, state:"Selangor", kelas:"Urban"},
    {kod:"P161", seat:"Pulai", name:"Nur Jazlan Mohamed", party:"BN-UMNO", y:104761, color:colorBN, level:34, state:"Johor", kelas:"Urban"},
    {kod:"P137", seat:"Bukit Katil", name:"Shamsul Iskandar", party:"PKR", y:105163, color:colorOPP, level:34, state:"Melaka", kelas:"Urban"},
    {kod:"P097", seat:"Selayang", name:"William Leong Jee Keen", party:"PKR", y:108276, color:colorOPP, level:32, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P159", seat:"Pasir Gudang", name:"Normala Abdul Samad", party:"BN-UMNO", y:108896, color:colorBN, level:31, state:"Johor", kelas:"Semi-urban"},
    {kod:"P103", seat:"Puchong", name:"Gobind Singh Deo", party:"DAP", y:110187, color:colorOPP, level:30, state:"Selangor", kelas:"Urban"},
    {kod:"P111", seat:"Kota Raja", name:"Siti Mariah Mahmud", party:"AMANAH", y:110526, color:colorOPP, level:30, state:"Selangor", kelas:"Urban"},
    {kod:"P162", seat:"Gelang Patah", name:"Lim Kit Siang", party:"DAP", y:115227, color:colorOPP, level:26, state:"Johor", kelas:"Semi-urban"},
    {kod:"P098", seat:"Gombak", name:"Mohamed Azmin Ali", party:"PKR", y:124823, color:colorOPP, level:19, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P101", seat:"Hulu Langat", name:"Che Rosli Che Mat", party:"PAS", y:129527, color:colorOPP, level:16, state:"Selangor", kelas:"Semi-urban"},
    {kod:"P107", seat:"Subang", name:"R. Sivarasa", party:"PKR", y:130211, color:colorOPP, level:15, state:"Selangor", kelas:"Urban"},
    {kod:"P102", seat:"Serdang", name:"Ong Kian Ming", party:"DAP", y:139604, color:colorOPP, level:8, state:"Selangor", kelas:"Urban"},
    {kod:"P109", seat:"Kapar", name:"G. Manivannan", party:"PKR", y:146625, color:colorOPP, level:3, state:"Selangor", kelas:"Urban"},
];

var opponents =  [
    {kod:"P085", seat:"Pekan", name:"Mohd. Najib Abdul Razak", voter:82303, pos:"Prime Minister", level:51, party:"BN-UMNO"}, 
    {kod:"P044", seat:"Permatang Pauh", name:"Wan Azizah Wan Ismail", voter:74545, pos:"Opposition Leader", level:57, party:"PKR"}, 
    {kod:"P125", seat:"Putrajaya", name:"Tengku Adnan Tengku Mansor", voter:17925, pos:"Federal Minister", level:100, party:"BN-UMNO"}, 
    {kod:"P162", seat:"Gelang Patah", name:"Lim Kit Siang", voter:115227, pos:"MP", level:26, party:"DAP"}, 
    // {kod:"P037", seat:"Marang", name:"Abdul Hadi Awang", voter:96708, pos:"MP", level:40, party:"PAS"}, 
    // {kod:"P075", seat:"Bagan Datok", name:"Ahmad Zahid Hamidi", voter:39426, pos:"Deputy Prime Minister", level:84, party:"BN-UMNO"}, 
    {kod:"P102", seat:"Serdang", name:"Ong Kian Ming", voter:139604, pos:"MP", level:8, party:"DAP"}, 
    {kod:"P187", seat:"Kinabatangan", name:"Bung Moktar Radin", voter:25315, pos:"MP", level:94, party:"BN-UMNO"}, 
    // {kod:"P131", seat:"Rembau", name:"Khairy Jamaluddin", voter:79154, pos:"Federal Minister", level:54, party:"BN-UMNO"}, 
    // {kod:"P089", seat:"Bentong", name:"Liow Tiong Lai", voter:62460, pos:"Federal Minister", level:66, party:"BN-MCA"},    
    // {kod:"P121", seat:"Lembah Pantai", name:"Nurul Izzah Anwar", voter:72675, pos:"MP", level:59, party:"PKR"}, 
    // {kod:"P115", seat:"Batu", name:"Tian Chua", voter:85092, pos:"MP", level:49, party:"PKR"}, 
];

var seatByState = [
  ["Padang Besar","Kangar","Arau"],
  ["Langkawi","Jerlun","Kubang Pasu","Padang Terap","Pokok Sena","Alor Star","Kuala Kedah","Pendang","Jerai","Sik","Merbok","Sungai Petani","Baling","Padang Serai","Kulim-Bandar Baharu"],
  ["Tumpat","Pengkalan Chepa","Kota Bharu","Pasir Mas","Rantau Panjang","Kubang Kerian","Bachok","Ketereh","Tanah Merah","Pasir Puteh","Machang","Jeli","Kuala Krai","Gua Musang"],
  ["Besut","Setiu","Kuala Nerus","Kuala Terengganu","Marang","Hulu Terengganu","Dungun","Kemaman"],
  ["Kepala Batas","Tasek Gelugor","Bagan","Permatang Pauh","Bukit Mertajam","Batu Kawan","Nibong Tebal","Bukit Bendera","Tanjong","Jelutong","Bukit Gelugor","Bayan Baru","Balik Pulau"],
  ["Gerik","Lenggong","Larut","Parit Buntar","Bagan Serai","Bukit Gantang","Taiping","Padang Rengas","Sungai Siput","Tambun","Ipoh Timor","Ipoh Barat","Batu Gajah","Kuala Kangsar","Beruas","Parit","Kampar","Gopeng","Tapah","Pasir Salak","Lumut","Bagan Datok","Telok Intan","Tanjong Malim"],
  ["Cameron Highlands","Lipis","Raub","Jerantut","Indera Mahkota","Kuantan","Paya Besar","Pekan","Maran","Kuala Krau","Temerloh","Bentong","Bera","Rompin"],
  ["Sabak Bernam","Sungai Besar","Hulu Selangor","Tanjong Karang","Kuala Selangor","Selayang","Gombak","Ampang","Pandan","Hulu Langat","Serdang","Puchong","Kelana Jaya","Petaling Jaya Selatan","Petaling Jaya Utara","Subang","Shah Alam","Kapar","Klang","Kota Raja","Kuala Langat","Sepang"],
  ["Kepong","Batu","Wangsa Maju","Segambut","Setiawangsa","Titiwangsa","Bukit Bintang","Lembah Pantai","Seputeh","Cheras","Bandar Tun Razak"],
  ["Putrajaya"],
  ["Jelebu","Jempol","Seremban","Kuala Pilah","Rasah","Rembau","Telok Kemang","Tampin"],
  ["Masjid Tanah","Alor Gajah","Tangga Batu","Bukit Katil","Kota Melaka","Jasin"],
  ["Segamat","Sekijang","Labis","Pagoh","Ledang","Bakri","Muar","Parit Sulong","Ayer Hitam","Sri Gading","Batu Pahat","Simpang Renggam","Kluang","Sembrong","Mersing","Tenggara","Kota Tinggi","Pengerang","Tebrau","Pasir Gudang","Johor Bahru","Pulai","Gelang Patah","Kulai","Pontian","Tanjong Piai"],
  ["Labuan"],
  ["Kudat","Kota Marudu","Kota Belud","Tuaran","Sepanggar","Kota Kinabalu","Putatan","Penampang","Papar","Kimanis","Beaufort","Sipitang","Ranau","Keningau","Tenom","Pensiangan","Beluran","Libaran","Batu Sapi","Sandakan","Kinabatangan","Silam","Semporna","Tawau","Kalabakan"],
  ["Mas Gading","Santubong","Petra Jaya","Bandar Kuching","Stampin","Kota Samarahan","Puncak Borneo (previously Mambong)","Serian","Batang Sadong","Batang Lupar","Sri Aman","Lubok Antu","Betong","Saratok","Tanjong Manis","Igan","Sarikei","Julau","Kanowit","Lanang","Sibu","Mukah","Selangau","Kapit","Hulu Rajang","Bintulu","Sibuti","Miri","Baram","Limbang","Lawas"],
];